%YAML:1.0

cam0:
  T_imu_cam:
    - [ 0.0, -1.0,  0.0,  0.000]
    - [ 1.0,  0.0,  0.0,  0.000]
    - [ 0.0,  0.0,  1.0, -0.013]
    - [ 0.0,  0.0,  0.0,  1.0]
  camera_model: pinhole
  distortion_coeffs: [-0.15313255, 0.94508686, -2.24202974, 1.64559904]
  distortion_model: equidistant
  intrinsics: [342.98461795, 341.33762169, 327.061485, 248.34471403]
  resolution: [640, 480]
