%YAML:1.0

cam0:
  T_imu_cam:
    - [ 0, -1,  0,  0.000]
    - [ 1,  0,  0,  0.000]
    - [ 0,  0,  1, -0.013]
    - [ 0,  0,  0,      1]
  camera_model: pinhole
  distortion_coeffs: [-0.15313254960457973, 0.9450868593649776, -2.2420297405284617, 1.6455990400278733]
  distortion_model: equidistant
  intrinsics: [342.9846179532394, 341.3376216879097, 327.0614850020841, 248.34471402562463]
  resolution: [640, 480]
